
### yml 파일은 안됨.

spring:
  onams:
    datasource:
      hikari:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mariadb://enable81.iptime.org:3306/ONAMS?allowMultiQueries=true&autocommit=false
        username: ONAMS
        password: onbrid!8845
  otherdb:
    datasource:
      hikari:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mysql://localhost:43306/test
        username: onams
        password: onbrid8845


